Databases/TodoList_EFCore/TodoList/Models/Base/Entity.cs
using System;

namespace TodoList.Models.Base
{
    public abstract class Entity
    {
        public int Id { get; set; }

        public DateTime CreatedUtc { get; set; }
    }
}

Databases/TodoList_EFCore/TodoList/Models/Base/NamedEntity.cs
namespace TodoList.Models.Base
{
    public abstract class NamedEntity : Entity
    {
        public string Name { get; set; }
    }
}

Databases/TodoList_EFCore/TodoList/Models/Category.cs
using TodoList.Models.Base;

namespace TodoList.Models
{
    public class Category : NamedEntity
    {
    }
}

Databases/TodoList_EFCore/TodoList/Models/ErrorViewModel.cs
using System;

namespace TodoList.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Databases/TodoList_EFCore/TodoList/Models/Todo.cs
using TodoList.Models.Base;

namespace TodoList.Models
{
    public class Todo : NamedEntity
    {
        public string Category { get; set; }

        public User User { get; set; }

        public int? UserId { get; set; }
    }
}

Databases/TodoList_EFCore/TodoList/Models/User.cs
using System.Collections.Generic;
using TodoList.Models.Base;

namespace TodoList.Models
{
    public class User : Entity
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public List<Todo> Todos { get; set; }
    }
}

Databases/TodoList_EFCore/TodoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TodoList.Models;
using TodoList.Services;

namespace TodoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TodosService _todosService;

        public HomeController(ILogger<HomeController> logger, TodosService todosService)
        {
            _logger = logger;
            _todosService = todosService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Databases/TodoList_EFCore/TodoList/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using TodoList.Dtos;
using TodoList.Services;

namespace TodoList.Controllers
{
    public class TodoController : Controller
    {
        private TodosService _todosService;
        private UserService _userService;

        public TodoController(TodosService todosService, UserService userService)
        {
            _todosService = todosService;
            _userService = userService;
        }

        public IActionResult Index()
        {
            var todos = _todosService.GetAll();
            return View(todos);
        }

        [HttpGet]
        public IActionResult Add()
        {
            CreateTodoDto todo = new CreateTodoDto(); //Passing empty model
            todo.Todo = new Models.Todo();
            todo.Users = _userService.GetAll();
            return View(todo);
        }

        [HttpPost]
        public IActionResult Add(CreateTodoDto createTodo)
        {
            _todosService.Add(createTodo);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _todosService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Databases/TodoList_EFCore/TodoList/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using TodoList.Dtos;
using TodoList.Models;
using TodoList.Services;

namespace TodoList.Controllers;

public class UserController : Controller
{
    private readonly UserService _userService;

    public UserController(UserService userService)
    {
        _userService = userService;
    }

    public IActionResult Index()
    {
        List<UserDto> users = _userService.GetAll();
        return View(users);
    }

    [HttpGet]
    public IActionResult Add()
    {
        var user = new User();
        return View(user);
    }

    [HttpPost]
    public IActionResult Add(User user)
    {
        _userService.Add(user);
        return RedirectToAction("Index");
    }
}

Databases/TodoList_EFCore/TodoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todos List</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Add">Add Todo</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User List</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Add">Add User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TodoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Databases/TodoList_EFCore/TodoList/Views/Todo/Add.cshtml
@using TodoList.Dtos
@model CreateTodoDto

<h2>Register</h2>

@using (Html.BeginForm("Add", "Todo", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(a => a.Todo.Name)
        @Html.TextBoxFor(a => a.Todo.Name, "", new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Todo.Category)
        @Html.TextBoxFor(a => a.Todo.Category, "", new {@class = "form-control"})
     </div>

      <div class="form-group">
        @Html.LabelFor(a => a.Todo.CreatedUtc)
        @Html.TextBoxFor(a => a.Todo.CreatedUtc, new {@class = "form-control"})
    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.Todo.UserId)
        @Html.DropDownListFor(a => a.Todo.UserId, new SelectList(@Model.Users, "Id", "FullName"), "", new {@class = "form-control"} )
    </div>
        
    <input class="btn btn-primary" type="submit" value="Submit"/>
}

Databases/TodoList_EFCore/TodoList/Views/Todo/Index.cshtml
@model List<Todo>

<h3>Testing Todos</h3>

<table>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Created</th>
      <th scope="col">Actions</th>
      
    </tr>
  </thead>
  <tbody>
      @foreach (var todo in @Model)
        {
        <tr>
          <th scope="row"></th>
          <td>@todo.Name</td>
          <td>@todo.Category</td>
         @* <td>@todo.CreatedUtc</td>*@
          <td>@Html.ActionLink("Remove", "Delete", "Todo", new { Name = @todo.Name})</td>
        </tr>
        }
    
    
  </tbody>
</table>

Databases/TodoList_EFCore/TodoList/Views/User/Add.cshtml
@model User

<h2>Register</h2>

@using (Html.BeginForm("Add", "User", FormMethod.Post))
{
    @Html.LabelFor(a => a.FirstName)
    @Html.TextBoxFor(a => a.FirstName)

    @Html.LabelFor(a => a.LastName)
    @Html.TextBoxFor(a => a.LastName)

  
        
    <input type="submit" value="Submit"/>
}

Databases/TodoList_EFCore/TodoList/Views/User/Index.cshtml
@using TodoList.Dtos
@model List<UserDto>

<h3>Testing Todos</h3>

<table>


<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">FullName</th>
    </tr>
  </thead>
  <tbody>
      @foreach (var todo in @Model)
        {
        <tr>
          <th scope="row"></th>
          <td>@todo.FullName</td>
        </tr>
        }
  </tbody>
</table>